### PR TITLE
Demonstrates working call to sentiment API

### PR DESCRIPTION
**Pull request by ChideraOkeke**
I wrote a function that returns a float point number between 1 and -1 when given a string.

### CODE REVIEW

**Review by CesarRiv — COMMENTED** [review]
Looks amazing LGTM!

**Comment by ChideraOkeke** [comment]
Also side note, the checks failed because the credentials were not available.  I have the credentials in my home directory on cloud shell.

**Comment by AshaBrianna** [comment]
> Also side note, the checks failed because the credentials were not available. I have the credentials in my home directory on cloud shell.

Got it, but the checks in place will not allow PRs to merge without passing the checks. Not sure how to work around the credential issue.

**Comment by SolaJr** [comment]
Awesome!

**Review by SolaJr — APPROVED** [review]

**Pull request closed without merging**
