### PR TITLE
Adjust DataStorage set up

### PR DESCRIPTION
**Pull request by AshaBrianna**
- incorporate SentimentAnalysis as a function within Entry.java
- adjust variable naming and types for consistency in all instances in files

### CODE REVIEW

**Review by CesarRiv — APPROVED** [review]
LGTM!

**Review by ChideraOkeke — COMMENTED** [review]
I am currently working on the JournalEntryServlet.java and I'm concerned that these changes will cause merge conflicts. It looks good but my branch is set up very differently.

**Comment by AshaBrianna** [comment]
> I am currently working on the JournalEntryServlet.java and I'm concerned that these changes will cause merge conflicts. It looks good but my branch is set up very differently.

Okay, I don't want to merge anything that will possibly conflict with your work. Just out of curiosity, what features are you adding to JournalEntryServlet.java?

**Comment by ChideraOkeke** [comment]
Sorry i've been MIA, yesterday was my birthday. I'm working on authentication and trying to figure out changes i might make to the way information is stored in Datastore. Since I haven't pushed anything, you can merge and I'll work with the changes on my end.

**Pull request closed without merging**
